/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_hris_client

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
	"strings"
	"time"
)

// Linger please
var (
	_ _context.Context
)

// TimeOffBalancesApiService TimeOffBalancesApi service
type TimeOffBalancesApiService service

type ApiTimeOffBalancesListRequest struct {
	ctx _context.Context
	ApiService *TimeOffBalancesApiService
	xAccountToken *string
	createdAfter *time.Time
	createdBefore *time.Time
	cursor *string
	employeeId *string
	includeDeletedData *bool
	includeRemoteData *bool
	modifiedAfter *time.Time
	modifiedBefore *time.Time
	pageSize *int32
	policyType *string
	remoteId *string
}

func (r ApiTimeOffBalancesListRequest) XAccountToken(xAccountToken string) ApiTimeOffBalancesListRequest {
	r.xAccountToken = &xAccountToken
	return r
}
func (r ApiTimeOffBalancesListRequest) CreatedAfter(createdAfter time.Time) ApiTimeOffBalancesListRequest {
	r.createdAfter = &createdAfter
	return r
}
func (r ApiTimeOffBalancesListRequest) CreatedBefore(createdBefore time.Time) ApiTimeOffBalancesListRequest {
	r.createdBefore = &createdBefore
	return r
}
func (r ApiTimeOffBalancesListRequest) Cursor(cursor string) ApiTimeOffBalancesListRequest {
	r.cursor = &cursor
	return r
}
func (r ApiTimeOffBalancesListRequest) EmployeeId(employeeId string) ApiTimeOffBalancesListRequest {
	r.employeeId = &employeeId
	return r
}
func (r ApiTimeOffBalancesListRequest) IncludeDeletedData(includeDeletedData bool) ApiTimeOffBalancesListRequest {
	r.includeDeletedData = &includeDeletedData
	return r
}
func (r ApiTimeOffBalancesListRequest) IncludeRemoteData(includeRemoteData bool) ApiTimeOffBalancesListRequest {
	r.includeRemoteData = &includeRemoteData
	return r
}
func (r ApiTimeOffBalancesListRequest) ModifiedAfter(modifiedAfter time.Time) ApiTimeOffBalancesListRequest {
	r.modifiedAfter = &modifiedAfter
	return r
}
func (r ApiTimeOffBalancesListRequest) ModifiedBefore(modifiedBefore time.Time) ApiTimeOffBalancesListRequest {
	r.modifiedBefore = &modifiedBefore
	return r
}
func (r ApiTimeOffBalancesListRequest) PageSize(pageSize int32) ApiTimeOffBalancesListRequest {
	r.pageSize = &pageSize
	return r
}
func (r ApiTimeOffBalancesListRequest) PolicyType(policyType string) ApiTimeOffBalancesListRequest {
	r.policyType = &policyType
	return r
}
func (r ApiTimeOffBalancesListRequest) RemoteId(remoteId string) ApiTimeOffBalancesListRequest {
	r.remoteId = &remoteId
	return r
}

func (r ApiTimeOffBalancesListRequest) Execute() (PaginatedTimeOffBalanceList, *_nethttp.Response, error) {
	return r.ApiService.TimeOffBalancesListExecute(r)
}

/*
 * TimeOffBalancesList Method for TimeOffBalancesList
 * Returns a list of `TimeOffBalance` objects.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiTimeOffBalancesListRequest
 */
func (a *TimeOffBalancesApiService) TimeOffBalancesList(ctx _context.Context) ApiTimeOffBalancesListRequest {
	return ApiTimeOffBalancesListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

/*
 * Execute executes the request
 * @return PaginatedTimeOffBalanceList
 */
func (a *TimeOffBalancesApiService) TimeOffBalancesListExecute(r ApiTimeOffBalancesListRequest) (PaginatedTimeOffBalanceList, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  PaginatedTimeOffBalanceList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TimeOffBalancesApiService.TimeOffBalancesList")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/time-off-balances"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.xAccountToken == nil {
		return localVarReturnValue, nil, reportError("xAccountToken is required and must be specified")
	}

	if r.createdAfter != nil {
		localVarQueryParams.Add("created_after", parameterToString(*r.createdAfter, ""))
	}
	if r.createdBefore != nil {
		localVarQueryParams.Add("created_before", parameterToString(*r.createdBefore, ""))
	}
	if r.cursor != nil {
		localVarQueryParams.Add("cursor", parameterToString(*r.cursor, ""))
	}
	if r.employeeId != nil {
		localVarQueryParams.Add("employee_id", parameterToString(*r.employeeId, ""))
	}
	if r.includeDeletedData != nil {
		localVarQueryParams.Add("include_deleted_data", parameterToString(*r.includeDeletedData, ""))
	}
	if r.includeRemoteData != nil {
		localVarQueryParams.Add("include_remote_data", parameterToString(*r.includeRemoteData, ""))
	}
	if r.modifiedAfter != nil {
		localVarQueryParams.Add("modified_after", parameterToString(*r.modifiedAfter, ""))
	}
	if r.modifiedBefore != nil {
		localVarQueryParams.Add("modified_before", parameterToString(*r.modifiedBefore, ""))
	}
	if r.pageSize != nil {
		localVarQueryParams.Add("page_size", parameterToString(*r.pageSize, ""))
	}
	if r.policyType != nil {
		localVarQueryParams.Add("policy_type", parameterToString(*r.policyType, ""))
	}
	if r.remoteId != nil {
		localVarQueryParams.Add("remote_id", parameterToString(*r.remoteId, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["X-Account-Token"] = parameterToString(*r.xAccountToken, "")
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["tokenAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiTimeOffBalancesRetrieveRequest struct {
	ctx _context.Context
	ApiService *TimeOffBalancesApiService
	xAccountToken *string
	id string
	includeRemoteData *bool
}

func (r ApiTimeOffBalancesRetrieveRequest) XAccountToken(xAccountToken string) ApiTimeOffBalancesRetrieveRequest {
	r.xAccountToken = &xAccountToken
	return r
}
func (r ApiTimeOffBalancesRetrieveRequest) IncludeRemoteData(includeRemoteData bool) ApiTimeOffBalancesRetrieveRequest {
	r.includeRemoteData = &includeRemoteData
	return r
}

func (r ApiTimeOffBalancesRetrieveRequest) Execute() (TimeOffBalance, *_nethttp.Response, error) {
	return r.ApiService.TimeOffBalancesRetrieveExecute(r)
}

/*
 * TimeOffBalancesRetrieve Method for TimeOffBalancesRetrieve
 * Returns a `TimeOffBalance` object with the given `id`.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id
 * @return ApiTimeOffBalancesRetrieveRequest
 */
func (a *TimeOffBalancesApiService) TimeOffBalancesRetrieve(ctx _context.Context, id string) ApiTimeOffBalancesRetrieveRequest {
	return ApiTimeOffBalancesRetrieveRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

/*
 * Execute executes the request
 * @return TimeOffBalance
 */
func (a *TimeOffBalancesApiService) TimeOffBalancesRetrieveExecute(r ApiTimeOffBalancesRetrieveRequest) (TimeOffBalance, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  TimeOffBalance
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TimeOffBalancesApiService.TimeOffBalancesRetrieve")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/time-off-balances/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", _neturl.PathEscape(parameterToString(r.id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.xAccountToken == nil {
		return localVarReturnValue, nil, reportError("xAccountToken is required and must be specified")
	}

	if r.includeRemoteData != nil {
		localVarQueryParams.Add("include_remote_data", parameterToString(*r.includeRemoteData, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["X-Account-Token"] = parameterToString(*r.xAccountToken, "")
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["tokenAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
