/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_hris_client

import (
	"encoding/json"
)

// EmployeeEndpointRequest struct for EmployeeEndpointRequest
type EmployeeEndpointRequest struct {
	Model EmployeeRequest `json:"model"`
}

// NewEmployeeEndpointRequest instantiates a new EmployeeEndpointRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeEndpointRequest(model EmployeeRequest) *EmployeeEndpointRequest {
	this := EmployeeEndpointRequest{}
	this.Model = model
	return &this
}

// NewEmployeeEndpointRequestWithDefaults instantiates a new EmployeeEndpointRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeEndpointRequestWithDefaults() *EmployeeEndpointRequest {
	this := EmployeeEndpointRequest{}
	return &this
}

// GetModel returns the Model field value
func (o *EmployeeEndpointRequest) GetModel() EmployeeRequest {
	if o == nil {
		var ret EmployeeRequest
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *EmployeeEndpointRequest) GetModelOk() (*EmployeeRequest, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *EmployeeEndpointRequest) SetModel(v EmployeeRequest) {
	o.Model = v
}

func (o EmployeeEndpointRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["model"] = o.Model
	}
	return json.Marshal(toSerialize)
}

type NullableEmployeeEndpointRequest struct {
	value *EmployeeEndpointRequest
	isSet bool
}

func (v NullableEmployeeEndpointRequest) Get() *EmployeeEndpointRequest {
	return v.value
}

func (v *NullableEmployeeEndpointRequest) Set(val *EmployeeEndpointRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeEndpointRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeEndpointRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeEndpointRequest(val *EmployeeEndpointRequest) *NullableEmployeeEndpointRequest {
	return &NullableEmployeeEndpointRequest{value: val, isSet: true}
}

func (v NullableEmployeeEndpointRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeEndpointRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


