/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_hris_client

import (
	"encoding/json"
	"fmt"
)

// FlsaStatusEnum the model 'FlsaStatusEnum'
type FlsaStatusEnum string

// List of FlsaStatusEnum
const (
	EXEMPT FlsaStatusEnum = "EXEMPT"
	SALARIED_NONEXEMPT FlsaStatusEnum = "SALARIED_NONEXEMPT"
	NONEXEMPT FlsaStatusEnum = "NONEXEMPT"
	OWNER FlsaStatusEnum = "OWNER"
)

func (v *FlsaStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FlsaStatusEnum(value)
	for _, existing := range []FlsaStatusEnum{ "EXEMPT", "SALARIED_NONEXEMPT", "NONEXEMPT", "OWNER",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FlsaStatusEnum", value)
}

// Ptr returns reference to FlsaStatusEnum value
func (v FlsaStatusEnum) Ptr() *FlsaStatusEnum {
	return &v
}

type NullableFlsaStatusEnum struct {
	value *FlsaStatusEnum
	isSet bool
}

func (v NullableFlsaStatusEnum) Get() *FlsaStatusEnum {
	return v.value
}

func (v *NullableFlsaStatusEnum) Set(val *FlsaStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableFlsaStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableFlsaStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlsaStatusEnum(val *FlsaStatusEnum) *NullableFlsaStatusEnum {
	return &NullableFlsaStatusEnum{value: val, isSet: true}
}

func (v NullableFlsaStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlsaStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

