/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_hris_client

import (
	"encoding/json"
)

// DataPassthroughRequest # The DataPassthrough Object ### Description The `DataPassthrough` object is used to send information to an otherwise-unsupported third-party endpoint.  ### Usage Example Create a `DataPassthrough` to get team hierarchies from your Rippling integration.
type DataPassthroughRequest struct {
	Method string `json:"method"`
	Path string `json:"path"`
	BaseUrlOverride NullableString `json:"base_url_override,omitempty"`
	Data NullableString `json:"data,omitempty"`
	Headers map[string]interface{} `json:"headers,omitempty"`
	RequestFormat *string `json:"request_format,omitempty"`
}

// NewDataPassthroughRequest instantiates a new DataPassthroughRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataPassthroughRequest(method string, path string) *DataPassthroughRequest {
	this := DataPassthroughRequest{}
	this.Method = method
	this.Path = path
	return &this
}

// NewDataPassthroughRequestWithDefaults instantiates a new DataPassthroughRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataPassthroughRequestWithDefaults() *DataPassthroughRequest {
	this := DataPassthroughRequest{}
	return &this
}

// GetMethod returns the Method field value
func (o *DataPassthroughRequest) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *DataPassthroughRequest) GetMethodOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *DataPassthroughRequest) SetMethod(v string) {
	o.Method = v
}

// GetPath returns the Path field value
func (o *DataPassthroughRequest) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *DataPassthroughRequest) GetPathOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *DataPassthroughRequest) SetPath(v string) {
	o.Path = v
}

// GetBaseUrlOverride returns the BaseUrlOverride field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DataPassthroughRequest) GetBaseUrlOverride() string {
	if o == nil || o.BaseUrlOverride.Get() == nil {
		var ret string
		return ret
	}
	return *o.BaseUrlOverride.Get()
}

// GetBaseUrlOverrideOk returns a tuple with the BaseUrlOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DataPassthroughRequest) GetBaseUrlOverrideOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.BaseUrlOverride.Get(), o.BaseUrlOverride.IsSet()
}

// HasBaseUrlOverride returns a boolean if a field has been set.
func (o *DataPassthroughRequest) HasBaseUrlOverride() bool {
	if o != nil && o.BaseUrlOverride.IsSet() {
		return true
	}

	return false
}

// SetBaseUrlOverride gets a reference to the given NullableString and assigns it to the BaseUrlOverride field.
func (o *DataPassthroughRequest) SetBaseUrlOverride(v string) {
	o.BaseUrlOverride.Set(&v)
}
// SetBaseUrlOverrideNil sets the value for BaseUrlOverride to be an explicit nil
func (o *DataPassthroughRequest) SetBaseUrlOverrideNil() {
	o.BaseUrlOverride.Set(nil)
}

// UnsetBaseUrlOverride ensures that no value is present for BaseUrlOverride, not even an explicit nil
func (o *DataPassthroughRequest) UnsetBaseUrlOverride() {
	o.BaseUrlOverride.Unset()
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DataPassthroughRequest) GetData() string {
	if o == nil || o.Data.Get() == nil {
		var ret string
		return ret
	}
	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DataPassthroughRequest) GetDataOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// HasData returns a boolean if a field has been set.
func (o *DataPassthroughRequest) HasData() bool {
	if o != nil && o.Data.IsSet() {
		return true
	}

	return false
}

// SetData gets a reference to the given NullableString and assigns it to the Data field.
func (o *DataPassthroughRequest) SetData(v string) {
	o.Data.Set(&v)
}
// SetDataNil sets the value for Data to be an explicit nil
func (o *DataPassthroughRequest) SetDataNil() {
	o.Data.Set(nil)
}

// UnsetData ensures that no value is present for Data, not even an explicit nil
func (o *DataPassthroughRequest) UnsetData() {
	o.Data.Unset()
}

// GetHeaders returns the Headers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DataPassthroughRequest) GetHeaders() map[string]interface{} {
	if o == nil  {
		var ret map[string]interface{}
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DataPassthroughRequest) GetHeadersOk() (*map[string]interface{}, bool) {
	if o == nil || o.Headers == nil {
		return nil, false
	}
	return &o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *DataPassthroughRequest) HasHeaders() bool {
	if o != nil && o.Headers != nil {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]interface{} and assigns it to the Headers field.
func (o *DataPassthroughRequest) SetHeaders(v map[string]interface{}) {
	o.Headers = v
}

// GetRequestFormat returns the RequestFormat field value if set, zero value otherwise.
func (o *DataPassthroughRequest) GetRequestFormat() string {
	if o == nil || o.RequestFormat == nil {
		var ret string
		return ret
	}
	return *o.RequestFormat
}

// GetRequestFormatOk returns a tuple with the RequestFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataPassthroughRequest) GetRequestFormatOk() (*string, bool) {
	if o == nil || o.RequestFormat == nil {
		return nil, false
	}
	return o.RequestFormat, true
}

// HasRequestFormat returns a boolean if a field has been set.
func (o *DataPassthroughRequest) HasRequestFormat() bool {
	if o != nil && o.RequestFormat != nil {
		return true
	}

	return false
}

// SetRequestFormat gets a reference to the given string and assigns it to the RequestFormat field.
func (o *DataPassthroughRequest) SetRequestFormat(v string) {
	o.RequestFormat = &v
}

func (o DataPassthroughRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["method"] = o.Method
	}
	if true {
		toSerialize["path"] = o.Path
	}
	if o.BaseUrlOverride.IsSet() {
		toSerialize["base_url_override"] = o.BaseUrlOverride.Get()
	}
	if o.Data.IsSet() {
		toSerialize["data"] = o.Data.Get()
	}
	if o.Headers != nil {
		toSerialize["headers"] = o.Headers
	}
	if o.RequestFormat != nil {
		toSerialize["request_format"] = o.RequestFormat
	}
	return json.Marshal(toSerialize)
}

type NullableDataPassthroughRequest struct {
	value *DataPassthroughRequest
	isSet bool
}

func (v NullableDataPassthroughRequest) Get() *DataPassthroughRequest {
	return v.value
}

func (v *NullableDataPassthroughRequest) Set(val *DataPassthroughRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDataPassthroughRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDataPassthroughRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataPassthroughRequest(val *DataPassthroughRequest) *NullableDataPassthroughRequest {
	return &NullableDataPassthroughRequest{value: val, isSet: true}
}

func (v NullableDataPassthroughRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataPassthroughRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


