/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_hris_client

import (
	"encoding/json"
	"fmt"
)

// CountryEnum the model 'CountryEnum'
type CountryEnum string

// apologies but this is to get around an import error
var _ = fmt.Printf
// List of CountryEnum
const (
    COUNTRYENUM_MERGE_NONSTANDARD_VALUE CountryEnum = "MERGE_NONSTANDARD_VALUE"
    
	COUNTRYENUM_AF CountryEnum = "AF"
	COUNTRYENUM_AX CountryEnum = "AX"
	COUNTRYENUM_AL CountryEnum = "AL"
	COUNTRYENUM_DZ CountryEnum = "DZ"
	COUNTRYENUM_AS CountryEnum = "AS"
	COUNTRYENUM_AD CountryEnum = "AD"
	COUNTRYENUM_AO CountryEnum = "AO"
	COUNTRYENUM_AI CountryEnum = "AI"
	COUNTRYENUM_AQ CountryEnum = "AQ"
	COUNTRYENUM_AG CountryEnum = "AG"
	COUNTRYENUM_AR CountryEnum = "AR"
	COUNTRYENUM_AM CountryEnum = "AM"
	COUNTRYENUM_AW CountryEnum = "AW"
	COUNTRYENUM_AU CountryEnum = "AU"
	COUNTRYENUM_AT CountryEnum = "AT"
	COUNTRYENUM_AZ CountryEnum = "AZ"
	COUNTRYENUM_BS CountryEnum = "BS"
	COUNTRYENUM_BH CountryEnum = "BH"
	COUNTRYENUM_BD CountryEnum = "BD"
	COUNTRYENUM_BB CountryEnum = "BB"
	COUNTRYENUM_BY CountryEnum = "BY"
	COUNTRYENUM_BE CountryEnum = "BE"
	COUNTRYENUM_BZ CountryEnum = "BZ"
	COUNTRYENUM_BJ CountryEnum = "BJ"
	COUNTRYENUM_BM CountryEnum = "BM"
	COUNTRYENUM_BT CountryEnum = "BT"
	COUNTRYENUM_BO CountryEnum = "BO"
	COUNTRYENUM_BQ CountryEnum = "BQ"
	COUNTRYENUM_BA CountryEnum = "BA"
	COUNTRYENUM_BW CountryEnum = "BW"
	COUNTRYENUM_BV CountryEnum = "BV"
	COUNTRYENUM_BR CountryEnum = "BR"
	COUNTRYENUM_IO CountryEnum = "IO"
	COUNTRYENUM_BN CountryEnum = "BN"
	COUNTRYENUM_BG CountryEnum = "BG"
	COUNTRYENUM_BF CountryEnum = "BF"
	COUNTRYENUM_BI CountryEnum = "BI"
	COUNTRYENUM_CV CountryEnum = "CV"
	COUNTRYENUM_KH CountryEnum = "KH"
	COUNTRYENUM_CM CountryEnum = "CM"
	COUNTRYENUM_CA CountryEnum = "CA"
	COUNTRYENUM_KY CountryEnum = "KY"
	COUNTRYENUM_CF CountryEnum = "CF"
	COUNTRYENUM_TD CountryEnum = "TD"
	COUNTRYENUM_CL CountryEnum = "CL"
	COUNTRYENUM_CN CountryEnum = "CN"
	COUNTRYENUM_CX CountryEnum = "CX"
	COUNTRYENUM_CC CountryEnum = "CC"
	COUNTRYENUM_CO CountryEnum = "CO"
	COUNTRYENUM_KM CountryEnum = "KM"
	COUNTRYENUM_CG CountryEnum = "CG"
	COUNTRYENUM_CD CountryEnum = "CD"
	COUNTRYENUM_CK CountryEnum = "CK"
	COUNTRYENUM_CR CountryEnum = "CR"
	COUNTRYENUM_CI CountryEnum = "CI"
	COUNTRYENUM_HR CountryEnum = "HR"
	COUNTRYENUM_CU CountryEnum = "CU"
	COUNTRYENUM_CW CountryEnum = "CW"
	COUNTRYENUM_CY CountryEnum = "CY"
	COUNTRYENUM_CZ CountryEnum = "CZ"
	COUNTRYENUM_DK CountryEnum = "DK"
	COUNTRYENUM_DJ CountryEnum = "DJ"
	COUNTRYENUM_DM CountryEnum = "DM"
	COUNTRYENUM_DO CountryEnum = "DO"
	COUNTRYENUM_EC CountryEnum = "EC"
	COUNTRYENUM_EG CountryEnum = "EG"
	COUNTRYENUM_SV CountryEnum = "SV"
	COUNTRYENUM_GQ CountryEnum = "GQ"
	COUNTRYENUM_ER CountryEnum = "ER"
	COUNTRYENUM_EE CountryEnum = "EE"
	COUNTRYENUM_SZ CountryEnum = "SZ"
	COUNTRYENUM_ET CountryEnum = "ET"
	COUNTRYENUM_FK CountryEnum = "FK"
	COUNTRYENUM_FO CountryEnum = "FO"
	COUNTRYENUM_FJ CountryEnum = "FJ"
	COUNTRYENUM_FI CountryEnum = "FI"
	COUNTRYENUM_FR CountryEnum = "FR"
	COUNTRYENUM_GF CountryEnum = "GF"
	COUNTRYENUM_PF CountryEnum = "PF"
	COUNTRYENUM_TF CountryEnum = "TF"
	COUNTRYENUM_GA CountryEnum = "GA"
	COUNTRYENUM_GM CountryEnum = "GM"
	COUNTRYENUM_GE CountryEnum = "GE"
	COUNTRYENUM_DE CountryEnum = "DE"
	COUNTRYENUM_GH CountryEnum = "GH"
	COUNTRYENUM_GI CountryEnum = "GI"
	COUNTRYENUM_GR CountryEnum = "GR"
	COUNTRYENUM_GL CountryEnum = "GL"
	COUNTRYENUM_GD CountryEnum = "GD"
	COUNTRYENUM_GP CountryEnum = "GP"
	COUNTRYENUM_GU CountryEnum = "GU"
	COUNTRYENUM_GT CountryEnum = "GT"
	COUNTRYENUM_GG CountryEnum = "GG"
	COUNTRYENUM_GN CountryEnum = "GN"
	COUNTRYENUM_GW CountryEnum = "GW"
	COUNTRYENUM_GY CountryEnum = "GY"
	COUNTRYENUM_HT CountryEnum = "HT"
	COUNTRYENUM_HM CountryEnum = "HM"
	COUNTRYENUM_VA CountryEnum = "VA"
	COUNTRYENUM_HN CountryEnum = "HN"
	COUNTRYENUM_HK CountryEnum = "HK"
	COUNTRYENUM_HU CountryEnum = "HU"
	COUNTRYENUM_IS CountryEnum = "IS"
	COUNTRYENUM_IN CountryEnum = "IN"
	COUNTRYENUM_ID CountryEnum = "ID"
	COUNTRYENUM_IR CountryEnum = "IR"
	COUNTRYENUM_IQ CountryEnum = "IQ"
	COUNTRYENUM_IE CountryEnum = "IE"
	COUNTRYENUM_IM CountryEnum = "IM"
	COUNTRYENUM_IL CountryEnum = "IL"
	COUNTRYENUM_IT CountryEnum = "IT"
	COUNTRYENUM_JM CountryEnum = "JM"
	COUNTRYENUM_JP CountryEnum = "JP"
	COUNTRYENUM_JE CountryEnum = "JE"
	COUNTRYENUM_JO CountryEnum = "JO"
	COUNTRYENUM_KZ CountryEnum = "KZ"
	COUNTRYENUM_KE CountryEnum = "KE"
	COUNTRYENUM_KI CountryEnum = "KI"
	COUNTRYENUM_KW CountryEnum = "KW"
	COUNTRYENUM_KG CountryEnum = "KG"
	COUNTRYENUM_LA CountryEnum = "LA"
	COUNTRYENUM_LV CountryEnum = "LV"
	COUNTRYENUM_LB CountryEnum = "LB"
	COUNTRYENUM_LS CountryEnum = "LS"
	COUNTRYENUM_LR CountryEnum = "LR"
	COUNTRYENUM_LY CountryEnum = "LY"
	COUNTRYENUM_LI CountryEnum = "LI"
	COUNTRYENUM_LT CountryEnum = "LT"
	COUNTRYENUM_LU CountryEnum = "LU"
	COUNTRYENUM_MO CountryEnum = "MO"
	COUNTRYENUM_MG CountryEnum = "MG"
	COUNTRYENUM_MW CountryEnum = "MW"
	COUNTRYENUM_MY CountryEnum = "MY"
	COUNTRYENUM_MV CountryEnum = "MV"
	COUNTRYENUM_ML CountryEnum = "ML"
	COUNTRYENUM_MT CountryEnum = "MT"
	COUNTRYENUM_MH CountryEnum = "MH"
	COUNTRYENUM_MQ CountryEnum = "MQ"
	COUNTRYENUM_MR CountryEnum = "MR"
	COUNTRYENUM_MU CountryEnum = "MU"
	COUNTRYENUM_YT CountryEnum = "YT"
	COUNTRYENUM_MX CountryEnum = "MX"
	COUNTRYENUM_FM CountryEnum = "FM"
	COUNTRYENUM_MD CountryEnum = "MD"
	COUNTRYENUM_MC CountryEnum = "MC"
	COUNTRYENUM_MN CountryEnum = "MN"
	COUNTRYENUM_ME CountryEnum = "ME"
	COUNTRYENUM_MS CountryEnum = "MS"
	COUNTRYENUM_MA CountryEnum = "MA"
	COUNTRYENUM_MZ CountryEnum = "MZ"
	COUNTRYENUM_MM CountryEnum = "MM"
	COUNTRYENUM_NA CountryEnum = "NA"
	COUNTRYENUM_NR CountryEnum = "NR"
	COUNTRYENUM_NP CountryEnum = "NP"
	COUNTRYENUM_NL CountryEnum = "NL"
	COUNTRYENUM_NC CountryEnum = "NC"
	COUNTRYENUM_NZ CountryEnum = "NZ"
	COUNTRYENUM_NI CountryEnum = "NI"
	COUNTRYENUM_NE CountryEnum = "NE"
	COUNTRYENUM_NG CountryEnum = "NG"
	COUNTRYENUM_NU CountryEnum = "NU"
	COUNTRYENUM_NF CountryEnum = "NF"
	COUNTRYENUM_KP CountryEnum = "KP"
	COUNTRYENUM_MK CountryEnum = "MK"
	COUNTRYENUM_MP CountryEnum = "MP"
	COUNTRYENUM_NO CountryEnum = "NO"
	COUNTRYENUM_OM CountryEnum = "OM"
	COUNTRYENUM_PK CountryEnum = "PK"
	COUNTRYENUM_PW CountryEnum = "PW"
	COUNTRYENUM_PS CountryEnum = "PS"
	COUNTRYENUM_PA CountryEnum = "PA"
	COUNTRYENUM_PG CountryEnum = "PG"
	COUNTRYENUM_PY CountryEnum = "PY"
	COUNTRYENUM_PE CountryEnum = "PE"
	COUNTRYENUM_PH CountryEnum = "PH"
	COUNTRYENUM_PN CountryEnum = "PN"
	COUNTRYENUM_PL CountryEnum = "PL"
	COUNTRYENUM_PT CountryEnum = "PT"
	COUNTRYENUM_PR CountryEnum = "PR"
	COUNTRYENUM_QA CountryEnum = "QA"
	COUNTRYENUM_RE CountryEnum = "RE"
	COUNTRYENUM_RO CountryEnum = "RO"
	COUNTRYENUM_RU CountryEnum = "RU"
	COUNTRYENUM_RW CountryEnum = "RW"
	COUNTRYENUM_BL CountryEnum = "BL"
	COUNTRYENUM_SH CountryEnum = "SH"
	COUNTRYENUM_KN CountryEnum = "KN"
	COUNTRYENUM_LC CountryEnum = "LC"
	COUNTRYENUM_MF CountryEnum = "MF"
	COUNTRYENUM_PM CountryEnum = "PM"
	COUNTRYENUM_VC CountryEnum = "VC"
	COUNTRYENUM_WS CountryEnum = "WS"
	COUNTRYENUM_SM CountryEnum = "SM"
	COUNTRYENUM_ST CountryEnum = "ST"
	COUNTRYENUM_SA CountryEnum = "SA"
	COUNTRYENUM_SN CountryEnum = "SN"
	COUNTRYENUM_RS CountryEnum = "RS"
	COUNTRYENUM_SC CountryEnum = "SC"
	COUNTRYENUM_SL CountryEnum = "SL"
	COUNTRYENUM_SG CountryEnum = "SG"
	COUNTRYENUM_SX CountryEnum = "SX"
	COUNTRYENUM_SK CountryEnum = "SK"
	COUNTRYENUM_SI CountryEnum = "SI"
	COUNTRYENUM_SB CountryEnum = "SB"
	COUNTRYENUM_SO CountryEnum = "SO"
	COUNTRYENUM_ZA CountryEnum = "ZA"
	COUNTRYENUM_GS CountryEnum = "GS"
	COUNTRYENUM_KR CountryEnum = "KR"
	COUNTRYENUM_SS CountryEnum = "SS"
	COUNTRYENUM_ES CountryEnum = "ES"
	COUNTRYENUM_LK CountryEnum = "LK"
	COUNTRYENUM_SD CountryEnum = "SD"
	COUNTRYENUM_SR CountryEnum = "SR"
	COUNTRYENUM_SJ CountryEnum = "SJ"
	COUNTRYENUM_SE CountryEnum = "SE"
	COUNTRYENUM_CH CountryEnum = "CH"
	COUNTRYENUM_SY CountryEnum = "SY"
	COUNTRYENUM_TW CountryEnum = "TW"
	COUNTRYENUM_TJ CountryEnum = "TJ"
	COUNTRYENUM_TZ CountryEnum = "TZ"
	COUNTRYENUM_TH CountryEnum = "TH"
	COUNTRYENUM_TL CountryEnum = "TL"
	COUNTRYENUM_TG CountryEnum = "TG"
	COUNTRYENUM_TK CountryEnum = "TK"
	COUNTRYENUM_TO CountryEnum = "TO"
	COUNTRYENUM_TT CountryEnum = "TT"
	COUNTRYENUM_TN CountryEnum = "TN"
	COUNTRYENUM_TR CountryEnum = "TR"
	COUNTRYENUM_TM CountryEnum = "TM"
	COUNTRYENUM_TC CountryEnum = "TC"
	COUNTRYENUM_TV CountryEnum = "TV"
	COUNTRYENUM_UG CountryEnum = "UG"
	COUNTRYENUM_UA CountryEnum = "UA"
	COUNTRYENUM_AE CountryEnum = "AE"
	COUNTRYENUM_GB CountryEnum = "GB"
	COUNTRYENUM_UM CountryEnum = "UM"
	COUNTRYENUM_US CountryEnum = "US"
	COUNTRYENUM_UY CountryEnum = "UY"
	COUNTRYENUM_UZ CountryEnum = "UZ"
	COUNTRYENUM_VU CountryEnum = "VU"
	COUNTRYENUM_VE CountryEnum = "VE"
	COUNTRYENUM_VN CountryEnum = "VN"
	COUNTRYENUM_VG CountryEnum = "VG"
	COUNTRYENUM_VI CountryEnum = "VI"
	COUNTRYENUM_WF CountryEnum = "WF"
	COUNTRYENUM_EH CountryEnum = "EH"
	COUNTRYENUM_YE CountryEnum = "YE"
	COUNTRYENUM_ZM CountryEnum = "ZM"
	COUNTRYENUM_ZW CountryEnum = "ZW"
)

var allowedCountryEnumEnumValues = []CountryEnum{
	"AF",
	"AX",
	"AL",
	"DZ",
	"AS",
	"AD",
	"AO",
	"AI",
	"AQ",
	"AG",
	"AR",
	"AM",
	"AW",
	"AU",
	"AT",
	"AZ",
	"BS",
	"BH",
	"BD",
	"BB",
	"BY",
	"BE",
	"BZ",
	"BJ",
	"BM",
	"BT",
	"BO",
	"BQ",
	"BA",
	"BW",
	"BV",
	"BR",
	"IO",
	"BN",
	"BG",
	"BF",
	"BI",
	"CV",
	"KH",
	"CM",
	"CA",
	"KY",
	"CF",
	"TD",
	"CL",
	"CN",
	"CX",
	"CC",
	"CO",
	"KM",
	"CG",
	"CD",
	"CK",
	"CR",
	"CI",
	"HR",
	"CU",
	"CW",
	"CY",
	"CZ",
	"DK",
	"DJ",
	"DM",
	"DO",
	"EC",
	"EG",
	"SV",
	"GQ",
	"ER",
	"EE",
	"SZ",
	"ET",
	"FK",
	"FO",
	"FJ",
	"FI",
	"FR",
	"GF",
	"PF",
	"TF",
	"GA",
	"GM",
	"GE",
	"DE",
	"GH",
	"GI",
	"GR",
	"GL",
	"GD",
	"GP",
	"GU",
	"GT",
	"GG",
	"GN",
	"GW",
	"GY",
	"HT",
	"HM",
	"VA",
	"HN",
	"HK",
	"HU",
	"IS",
	"IN",
	"ID",
	"IR",
	"IQ",
	"IE",
	"IM",
	"IL",
	"IT",
	"JM",
	"JP",
	"JE",
	"JO",
	"KZ",
	"KE",
	"KI",
	"KW",
	"KG",
	"LA",
	"LV",
	"LB",
	"LS",
	"LR",
	"LY",
	"LI",
	"LT",
	"LU",
	"MO",
	"MG",
	"MW",
	"MY",
	"MV",
	"ML",
	"MT",
	"MH",
	"MQ",
	"MR",
	"MU",
	"YT",
	"MX",
	"FM",
	"MD",
	"MC",
	"MN",
	"ME",
	"MS",
	"MA",
	"MZ",
	"MM",
	"NA",
	"NR",
	"NP",
	"NL",
	"NC",
	"NZ",
	"NI",
	"NE",
	"NG",
	"NU",
	"NF",
	"KP",
	"MK",
	"MP",
	"NO",
	"OM",
	"PK",
	"PW",
	"PS",
	"PA",
	"PG",
	"PY",
	"PE",
	"PH",
	"PN",
	"PL",
	"PT",
	"PR",
	"QA",
	"RE",
	"RO",
	"RU",
	"RW",
	"BL",
	"SH",
	"KN",
	"LC",
	"MF",
	"PM",
	"VC",
	"WS",
	"SM",
	"ST",
	"SA",
	"SN",
	"RS",
	"SC",
	"SL",
	"SG",
	"SX",
	"SK",
	"SI",
	"SB",
	"SO",
	"ZA",
	"GS",
	"KR",
	"SS",
	"ES",
	"LK",
	"SD",
	"SR",
	"SJ",
	"SE",
	"CH",
	"SY",
	"TW",
	"TJ",
	"TZ",
	"TH",
	"TL",
	"TG",
	"TK",
	"TO",
	"TT",
	"TN",
	"TR",
	"TM",
	"TC",
	"TV",
	"UG",
	"UA",
	"AE",
	"GB",
	"UM",
	"US",
	"UY",
	"UZ",
	"VU",
	"VE",
	"VN",
	"VG",
	"VI",
	"WF",
	"EH",
	"YE",
	"ZM",
	"ZW",
}

func (v *CountryEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CountryEnum(value)
	for _, existing := range allowedCountryEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}
    *v = COUNTRYENUM_MERGE_NONSTANDARD_VALUE
    return nil
}

// NewCountryEnumFromValue returns a pointer to a valid CountryEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCountryEnumFromValue(v string) (*CountryEnum, error) {
	ev := CountryEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
        ev := COUNTRYENUM_MERGE_NONSTANDARD_VALUE
        return &ev, nil
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CountryEnum) IsValid() bool {
	for _, existing := range allowedCountryEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CountryEnum value
func (v CountryEnum) Ptr() *CountryEnum {
	return &v
}

type NullableCountryEnum struct {
	value *CountryEnum
	isSet bool
}

func (v NullableCountryEnum) Get() *CountryEnum {
	return v.value
}

func (v *NullableCountryEnum) Set(val *CountryEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableCountryEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableCountryEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCountryEnum(val *CountryEnum) *NullableCountryEnum {
	return &NullableCountryEnum{value: val, isSet: true}
}

func (v NullableCountryEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCountryEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

