/*
 * Merge HRIS API
 *
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_hris_client

import (
	"encoding/json"
	"time"
)

// EmploymentRequest # The Employment Object ### Description The `Employment` object is used to represent an employment position at a company. These are associated with the employee filling the role.  ### Usage Example Fetch from the `LIST Employments` endpoint and filter by `ID` to show all employees.
type EmploymentRequest struct {
	// The third-party API ID of the matching object.
	RemoteId NullableString `json:"remote_id,omitempty"`
	// The position's title.
	JobTitle NullableString `json:"job_title,omitempty"`
	// The position's pay rate in dollars.
	PayRate NullableFloat32 `json:"pay_rate,omitempty"`
	// The time period this pay rate encompasses.
	PayPeriod NullablePayPeriodEnum `json:"pay_period,omitempty"`
	// The position's pay frequency.
	PayFrequency NullablePayFrequencyEnum `json:"pay_frequency,omitempty"`
	// The position's currency code.
	PayCurrency NullablePayCurrencyEnum `json:"pay_currency,omitempty"`
	// The position's FLSA status.
	FlsaStatus NullableFlsaStatusEnum `json:"flsa_status,omitempty"`
	// The position's effective date.
	EffectiveDate NullableTime `json:"effective_date,omitempty"`
	// The position's type of employment.
	EmploymentType NullableEmploymentTypeEnum `json:"employment_type,omitempty"`
}

// NewEmploymentRequest instantiates a new EmploymentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmploymentRequest() *EmploymentRequest {
	this := EmploymentRequest{}
	return &this
}

// NewEmploymentRequestWithDefaults instantiates a new EmploymentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmploymentRequestWithDefaults() *EmploymentRequest {
	this := EmploymentRequest{}
	return &this
}

// GetRemoteId returns the RemoteId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmploymentRequest) GetRemoteId() string {
	if o == nil || o.RemoteId.Get() == nil {
		var ret string
		return ret
	}
	return *o.RemoteId.Get()
}

// GetRemoteIdOk returns a tuple with the RemoteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmploymentRequest) GetRemoteIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RemoteId.Get(), o.RemoteId.IsSet()
}

// HasRemoteId returns a boolean if a field has been set.
func (o *EmploymentRequest) HasRemoteId() bool {
	if o != nil && o.RemoteId.IsSet() {
		return true
	}

	return false
}

// SetRemoteId gets a reference to the given NullableString and assigns it to the RemoteId field.
func (o *EmploymentRequest) SetRemoteId(v string) {
	o.RemoteId.Set(&v)
}
// SetRemoteIdNil sets the value for RemoteId to be an explicit nil
func (o *EmploymentRequest) SetRemoteIdNil() {
	o.RemoteId.Set(nil)
}

// UnsetRemoteId ensures that no value is present for RemoteId, not even an explicit nil
func (o *EmploymentRequest) UnsetRemoteId() {
	o.RemoteId.Unset()
}

// GetJobTitle returns the JobTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmploymentRequest) GetJobTitle() string {
	if o == nil || o.JobTitle.Get() == nil {
		var ret string
		return ret
	}
	return *o.JobTitle.Get()
}

// GetJobTitleOk returns a tuple with the JobTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmploymentRequest) GetJobTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.JobTitle.Get(), o.JobTitle.IsSet()
}

// HasJobTitle returns a boolean if a field has been set.
func (o *EmploymentRequest) HasJobTitle() bool {
	if o != nil && o.JobTitle.IsSet() {
		return true
	}

	return false
}

// SetJobTitle gets a reference to the given NullableString and assigns it to the JobTitle field.
func (o *EmploymentRequest) SetJobTitle(v string) {
	o.JobTitle.Set(&v)
}
// SetJobTitleNil sets the value for JobTitle to be an explicit nil
func (o *EmploymentRequest) SetJobTitleNil() {
	o.JobTitle.Set(nil)
}

// UnsetJobTitle ensures that no value is present for JobTitle, not even an explicit nil
func (o *EmploymentRequest) UnsetJobTitle() {
	o.JobTitle.Unset()
}

// GetPayRate returns the PayRate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmploymentRequest) GetPayRate() float32 {
	if o == nil || o.PayRate.Get() == nil {
		var ret float32
		return ret
	}
	return *o.PayRate.Get()
}

// GetPayRateOk returns a tuple with the PayRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmploymentRequest) GetPayRateOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PayRate.Get(), o.PayRate.IsSet()
}

// HasPayRate returns a boolean if a field has been set.
func (o *EmploymentRequest) HasPayRate() bool {
	if o != nil && o.PayRate.IsSet() {
		return true
	}

	return false
}

// SetPayRate gets a reference to the given NullableFloat32 and assigns it to the PayRate field.
func (o *EmploymentRequest) SetPayRate(v float32) {
	o.PayRate.Set(&v)
}
// SetPayRateNil sets the value for PayRate to be an explicit nil
func (o *EmploymentRequest) SetPayRateNil() {
	o.PayRate.Set(nil)
}

// UnsetPayRate ensures that no value is present for PayRate, not even an explicit nil
func (o *EmploymentRequest) UnsetPayRate() {
	o.PayRate.Unset()
}

// GetPayPeriod returns the PayPeriod field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmploymentRequest) GetPayPeriod() PayPeriodEnum {
	if o == nil || o.PayPeriod.Get() == nil {
		var ret PayPeriodEnum
		return ret
	}
	return *o.PayPeriod.Get()
}

// GetPayPeriodOk returns a tuple with the PayPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmploymentRequest) GetPayPeriodOk() (*PayPeriodEnum, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PayPeriod.Get(), o.PayPeriod.IsSet()
}

// HasPayPeriod returns a boolean if a field has been set.
func (o *EmploymentRequest) HasPayPeriod() bool {
	if o != nil && o.PayPeriod.IsSet() {
		return true
	}

	return false
}

// SetPayPeriod gets a reference to the given NullablePayPeriodEnum and assigns it to the PayPeriod field.
func (o *EmploymentRequest) SetPayPeriod(v PayPeriodEnum) {
	o.PayPeriod.Set(&v)
}
// SetPayPeriodNil sets the value for PayPeriod to be an explicit nil
func (o *EmploymentRequest) SetPayPeriodNil() {
	o.PayPeriod.Set(nil)
}

// UnsetPayPeriod ensures that no value is present for PayPeriod, not even an explicit nil
func (o *EmploymentRequest) UnsetPayPeriod() {
	o.PayPeriod.Unset()
}

// GetPayFrequency returns the PayFrequency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmploymentRequest) GetPayFrequency() PayFrequencyEnum {
	if o == nil || o.PayFrequency.Get() == nil {
		var ret PayFrequencyEnum
		return ret
	}
	return *o.PayFrequency.Get()
}

// GetPayFrequencyOk returns a tuple with the PayFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmploymentRequest) GetPayFrequencyOk() (*PayFrequencyEnum, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PayFrequency.Get(), o.PayFrequency.IsSet()
}

// HasPayFrequency returns a boolean if a field has been set.
func (o *EmploymentRequest) HasPayFrequency() bool {
	if o != nil && o.PayFrequency.IsSet() {
		return true
	}

	return false
}

// SetPayFrequency gets a reference to the given NullablePayFrequencyEnum and assigns it to the PayFrequency field.
func (o *EmploymentRequest) SetPayFrequency(v PayFrequencyEnum) {
	o.PayFrequency.Set(&v)
}
// SetPayFrequencyNil sets the value for PayFrequency to be an explicit nil
func (o *EmploymentRequest) SetPayFrequencyNil() {
	o.PayFrequency.Set(nil)
}

// UnsetPayFrequency ensures that no value is present for PayFrequency, not even an explicit nil
func (o *EmploymentRequest) UnsetPayFrequency() {
	o.PayFrequency.Unset()
}

// GetPayCurrency returns the PayCurrency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmploymentRequest) GetPayCurrency() PayCurrencyEnum {
	if o == nil || o.PayCurrency.Get() == nil {
		var ret PayCurrencyEnum
		return ret
	}
	return *o.PayCurrency.Get()
}

// GetPayCurrencyOk returns a tuple with the PayCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmploymentRequest) GetPayCurrencyOk() (*PayCurrencyEnum, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PayCurrency.Get(), o.PayCurrency.IsSet()
}

// HasPayCurrency returns a boolean if a field has been set.
func (o *EmploymentRequest) HasPayCurrency() bool {
	if o != nil && o.PayCurrency.IsSet() {
		return true
	}

	return false
}

// SetPayCurrency gets a reference to the given NullablePayCurrencyEnum and assigns it to the PayCurrency field.
func (o *EmploymentRequest) SetPayCurrency(v PayCurrencyEnum) {
	o.PayCurrency.Set(&v)
}
// SetPayCurrencyNil sets the value for PayCurrency to be an explicit nil
func (o *EmploymentRequest) SetPayCurrencyNil() {
	o.PayCurrency.Set(nil)
}

// UnsetPayCurrency ensures that no value is present for PayCurrency, not even an explicit nil
func (o *EmploymentRequest) UnsetPayCurrency() {
	o.PayCurrency.Unset()
}

// GetFlsaStatus returns the FlsaStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmploymentRequest) GetFlsaStatus() FlsaStatusEnum {
	if o == nil || o.FlsaStatus.Get() == nil {
		var ret FlsaStatusEnum
		return ret
	}
	return *o.FlsaStatus.Get()
}

// GetFlsaStatusOk returns a tuple with the FlsaStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmploymentRequest) GetFlsaStatusOk() (*FlsaStatusEnum, bool) {
	if o == nil  {
		return nil, false
	}
	return o.FlsaStatus.Get(), o.FlsaStatus.IsSet()
}

// HasFlsaStatus returns a boolean if a field has been set.
func (o *EmploymentRequest) HasFlsaStatus() bool {
	if o != nil && o.FlsaStatus.IsSet() {
		return true
	}

	return false
}

// SetFlsaStatus gets a reference to the given NullableFlsaStatusEnum and assigns it to the FlsaStatus field.
func (o *EmploymentRequest) SetFlsaStatus(v FlsaStatusEnum) {
	o.FlsaStatus.Set(&v)
}
// SetFlsaStatusNil sets the value for FlsaStatus to be an explicit nil
func (o *EmploymentRequest) SetFlsaStatusNil() {
	o.FlsaStatus.Set(nil)
}

// UnsetFlsaStatus ensures that no value is present for FlsaStatus, not even an explicit nil
func (o *EmploymentRequest) UnsetFlsaStatus() {
	o.FlsaStatus.Unset()
}

// GetEffectiveDate returns the EffectiveDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmploymentRequest) GetEffectiveDate() time.Time {
	if o == nil || o.EffectiveDate.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.EffectiveDate.Get()
}

// GetEffectiveDateOk returns a tuple with the EffectiveDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmploymentRequest) GetEffectiveDateOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.EffectiveDate.Get(), o.EffectiveDate.IsSet()
}

// HasEffectiveDate returns a boolean if a field has been set.
func (o *EmploymentRequest) HasEffectiveDate() bool {
	if o != nil && o.EffectiveDate.IsSet() {
		return true
	}

	return false
}

// SetEffectiveDate gets a reference to the given NullableTime and assigns it to the EffectiveDate field.
func (o *EmploymentRequest) SetEffectiveDate(v time.Time) {
	o.EffectiveDate.Set(&v)
}
// SetEffectiveDateNil sets the value for EffectiveDate to be an explicit nil
func (o *EmploymentRequest) SetEffectiveDateNil() {
	o.EffectiveDate.Set(nil)
}

// UnsetEffectiveDate ensures that no value is present for EffectiveDate, not even an explicit nil
func (o *EmploymentRequest) UnsetEffectiveDate() {
	o.EffectiveDate.Unset()
}

// GetEmploymentType returns the EmploymentType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmploymentRequest) GetEmploymentType() EmploymentTypeEnum {
	if o == nil || o.EmploymentType.Get() == nil {
		var ret EmploymentTypeEnum
		return ret
	}
	return *o.EmploymentType.Get()
}

// GetEmploymentTypeOk returns a tuple with the EmploymentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmploymentRequest) GetEmploymentTypeOk() (*EmploymentTypeEnum, bool) {
	if o == nil  {
		return nil, false
	}
	return o.EmploymentType.Get(), o.EmploymentType.IsSet()
}

// HasEmploymentType returns a boolean if a field has been set.
func (o *EmploymentRequest) HasEmploymentType() bool {
	if o != nil && o.EmploymentType.IsSet() {
		return true
	}

	return false
}

// SetEmploymentType gets a reference to the given NullableEmploymentTypeEnum and assigns it to the EmploymentType field.
func (o *EmploymentRequest) SetEmploymentType(v EmploymentTypeEnum) {
	o.EmploymentType.Set(&v)
}
// SetEmploymentTypeNil sets the value for EmploymentType to be an explicit nil
func (o *EmploymentRequest) SetEmploymentTypeNil() {
	o.EmploymentType.Set(nil)
}

// UnsetEmploymentType ensures that no value is present for EmploymentType, not even an explicit nil
func (o *EmploymentRequest) UnsetEmploymentType() {
	o.EmploymentType.Unset()
}

func (o EmploymentRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RemoteId.IsSet() {
		toSerialize["remote_id"] = o.RemoteId.Get()
	}
	if o.JobTitle.IsSet() {
		toSerialize["job_title"] = o.JobTitle.Get()
	}
	if o.PayRate.IsSet() {
		toSerialize["pay_rate"] = o.PayRate.Get()
	}
	if o.PayPeriod.IsSet() {
		toSerialize["pay_period"] = o.PayPeriod.Get()
	}
	if o.PayFrequency.IsSet() {
		toSerialize["pay_frequency"] = o.PayFrequency.Get()
	}
	if o.PayCurrency.IsSet() {
		toSerialize["pay_currency"] = o.PayCurrency.Get()
	}
	if o.FlsaStatus.IsSet() {
		toSerialize["flsa_status"] = o.FlsaStatus.Get()
	}
	if o.EffectiveDate.IsSet() {
		toSerialize["effective_date"] = o.EffectiveDate.Get()
	}
	if o.EmploymentType.IsSet() {
		toSerialize["employment_type"] = o.EmploymentType.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableEmploymentRequest struct {
	value *EmploymentRequest
	isSet bool
}

func (v NullableEmploymentRequest) Get() *EmploymentRequest {
	return v.value
}

func (v *NullableEmploymentRequest) Set(val *EmploymentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEmploymentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEmploymentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmploymentRequest(val *EmploymentRequest) *NullableEmploymentRequest {
	return &NullableEmploymentRequest{value: val, isSet: true}
}

func (v NullableEmploymentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmploymentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


