name: HRIS SDK Client

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: build
        run: |
          go mod download golang.org/x/oauth2 && go get golang.org/x/oauth2 && go build
      - name: test
        run: |
          go test -v
